In [1]:
# Python libraries
import os
from scipy.io import loadmat
import pandas as pd
import numpy as np
import itertools

In [2]:
# Using ipynb import functions defined in other nb
from ipynb.fs.defs.myfun_load_dataset import *

## Some info about the dataset

One-dimensional traffic data (x-coordinate). The data contains 3+ vehicles in one lane.

First, we interpolate the position data with timestamps to a reference time discretization. We filtered sequences of data where two or more vehicles are present in the camera frame.

### How to read these filenames?
* The first number refers to the camera (1,...,5)
* The second number is the day
* The third number refers to the sequence

### Observation
* sequence_data_1-1_1 is preprocessed <- there are scenes in which I have less vehichles than 3
* sequence_data1-1_1 is postprocessed

## Comparison btw datasets

In [3]:
# load .mat
par_dir = os.path.dirname(os.getcwd()) # parent dir
dir_name = par_dir + "/NN-interaction"

In [5]:
dflist1 = load_dataset(dir_name, 'post')
dflist2 = load_dataset(dir_name, 'pre') # there are scenes in which I have <=2 vehicles-

In [6]:
len(dflist1), len(dflist2) # I have 10 dataframes in both the lists

(10, 10)

# How to read a df in dflist?

dflist contains 10 dataframes, one corresponding for each couple camera+sequence.
Fixing one couple (1<=camera<=5,1<=seq<=2), I have that df represents:
1. rows = same scene:\
there are different cars, sampled at the same timestamps!\
(the number of cars in a scene is equal to the number of columns)
2. columns = same car\
but evolving in time?

In [7]:
df1 = dflist1[0]
df2 = dflist2[0]

Each row represents a scene, and we have info about the timestamps where we have the recorded positions, Nveh...

In [8]:
df1

,Tarr,Xarr,N. vehicles,cam,day,seq
0,"[9.440000000000001, 9.64, 9.840000000000002, 1...","[[29.373325674060805, 34.22142942994519, 38.50...",3,1,1,1
1,"[14.240000000000002, 14.440000000000001, 14.64]","[[47.39131045666992, 53.82017733698899, 60.334...",3,1,1,1
2,"[23.64, 23.840000000000003, 24.040000000000003...","[[39.20354853492598, 44.53373067590911, 50.344...",3,1,1,1
3,"[72.44, 72.64, 72.84, 73.04, 73.24000000000001...","[[2.7333870214228604, 7.903389478164454, 13.90...",3,1,1,1
4,"[84.24000000000001, 84.44000000000001, 84.64, ...","[[21.74922515152677, 27.637296392268254, 33.03...",3,1,1,1
5,"[131.64, 131.84, 132.04]","[[29.92533961013666, 36.085487468240274, 42.11...",3,1,1,1
6,"[148.04, 148.23999999999998, 148.44]","[[48.201888758537635, 52.58811573357667, 57.22...",3,1,1,1
7,"[161.64, 161.84, 162.04]","[[28.43130968766962, 34.76343487043734, 40.755...",3,1,1,1
8,"[164.04, 164.24, 164.44, 164.64]","[[1.6731532650716647, 7.263156064323007, 12.60...",3,1,1,1
9,"[215.64, 215.84, 216.04]","[[7.567157827915416, 13.423172011187404, 19.23...",3,1,1,1
10,"[216.64, 216.84, 217.04]","[[23.001240988631807, 30.50534908349185, 38.47...",3,1,1,1
11,"[235.84, 236.04, 236.24, 236.44, 236.64]","[[49.73996871298165, 55.69228375001319, 54.308...",3,1,1,1
12,"[240.64, 240.84, 241.04]","[[37.36149996003182, 43.06968178384626, 49.741...",3,1,1,1
13,"[253.64, 253.84, 254.04]","[[26.835507748982067, 32.197592050679624, 38.4...",3,1,1,1
14,"[262.64, 262.84, 263.04, 263.24, 263.44, 263.64]","[[34.133415565851664, 41.48362136740176, 45.61...",3,1,1,1
15,"[312.84, 313.03999999999996, 313.2399999999999...","[[40.285589971394444, 46.241816642378716, 51.5...",3,1,1,1
16,"[314.84, 315.03999999999996, 315.2399999999999...","[[14.499405454865304, 20.423438964220548, 26.4...",3,1,1,1
17,"[325.23999999999995, 325.44, 325.64, 325.84, 3...","[[31.505362037596136, 37.31749924443956, 42.99...",3,1,1,1
18,"[333.23999999999995, 333.44, 333.64, 333.84]","[[63.234797046684406, 69.45532780047769, 49.98...",3,1,1,1
19,"[354.03999999999996, 354.24, 354.4399999999999...","[[48.58337263003963, 54.537711061139476, 61.61...",3,1,1,1
20,"[363.43999999999994, 363.64, 363.84, 364.03999...","[[22.833457330462238, 27.563512370758243, 32.8...",3,1,1,1
21,"[386.64, 386.84, 387.03999999999996, 387.24, 3...","[[27.963298492935618, 33.593403386491055, 40.3...",3,1,1,1
22,"[431.84, 432.03999999999996, 432.24]","[[33.571409207332024, 39.74956986770364, 47.69...",3,1,1,1
23,"[446.24, 446.43999999999994, 446.64, 446.84]","[[17.084341335513113, 22.262377277423376, 27.8...",3,1,1,1
24,"[447.43999999999994, 447.64, 447.84, 448.03999...","[[45.013763763149534, 51.228035303868765, 58.7...",3,1,1,1
25,"[495.84, 496.03999999999996, 496.24]","[[39.783294326275644, 44.40945118649327, 49.05...",3,1,1,1
26,"[496.84, 497.03999999999996, 497.24, 497.44, 4...","[[32.920396969834904, 36.815487835107646, 39.5...",3,1,1,1
27,"[499.03999999999996, 499.24, 499.44]","[[45.16576677118827, 49.93397447350024, 55.318...",3,1,1,1
28,"[500.64, 500.84, 501.03999999999996]","[[36.49947975347175, 39.739569414224, 43.51970...",3,1,1,1
29,"[502.24, 502.44, 502.64, 502.84, 503.039999999...","[[33.19840612115097, 37.393497129138986, 41.00...",3,1,1,1
30,"[534.84, 535.04, 535.24]","[[34.7130081192123, 36.49965515019897, 38.1947...",3,1,1,1
31,"[573.84, 574.04, 574.24, 574.4399999999999]","[[42.76867896690451, 46.783822400413726, 49.47...",3,1,1,1
32,"[10.040000000000001, 10.240000000000002, 10.44...","[[33.53416673947536, 23.798978208313272, 29.51...",4,1,1,1
33,"[313.44, 313.64, 313.84]","[[25.393265987911025, 14.149174076204321, 19.4...",4,1,1,1